name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
     - name: 'Checkout GitHub Action'
       uses: actions/checkout@main

     - name: 'Login to GitHub Container Registry'
       uses: docker/login-action@v1
       with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.TOKEN}}

     - name: Build the Docker image
       run: |
        docker build . --tag ghcr.io/${{secrets.OWNER}}/${{vars.DOCKER_IMAGE}}:${{ github.run_number }}
        docker push ghcr.io/${{secrets.OWNER}}/${{vars.DOCKER_IMAGE}}:${{ github.run_number }}

     - name: Install dependencies
       run: npm i

     - name: Build UI
       run : npm run build
       
     - name: Test the app
       run: npm run test

  image:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@main
      - name: Name of the image with tag
        run: echo 'IMAGE ${{vars.DOCKER_IMAGE}}:${{ github.run_number }}'
  
