name: GC-UI-Publish
on: [push]
jobs:
publish-gc-ui-image:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Login to GitHub Container Registry
uses: docker/login-action@v1
with:
registry: ghcr.io
username: ${{ github.actor }}
password: ${{ secrets.TOKEN }}
- name: Build the gc-ui Docker image
run: |
       docker build . --tag ghcr.io/mohammed-sameeruddin/bootcamp-32-green-commute_app:latest
       docker run ghcr.io/mohammed-sameeruddin/bootcamp-32-green-commute_app:latest
       docker push ghcr.io/mohammed-sameeruddin/bootcamp-32-green-commute_app:latest